#!/bin/bash -ex
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

ensure_dependencies()
{
  yum update -y
  yum install -y git docker make golang
}

configure_docker()
{
  mkdir -p /etc/docker
  tee /etc/docker/daemon.json << EOF
{
  "hosts": [
    "tcp://0.0.0.0:2375",
    "unix:///var/run/docker.sock"
  ]
}
EOF

  service docker restart
  usermod -a -G docker ec2-user
}

configure_home()
{
  tee -a $HOME/.bash_profile << EOF

export GOPATH=\$HOME/go
export PATH=\$GOPATH/bin:$PATH
EOF

  source $HOME/.bash_profile
  go get -v -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login

  mkdir -p $HOME/.docker
  tee $HOME/.docker/config.json << EOF
{
	"credsStore": "ecr-login"
}
EOF
}
export -f configure_home

ensure_dependencies
configure_docker
su ec2-user -c "configure_home"