#!/bin/bash

yum update -y
yum install -y git docker

# Start and stop docker before writing daemon.json.
# When I started docker after writing dameon.json
# daemon.json was being deleted, I assume by first
# start of docker
service docker start
service docker stop

# Allow connecting to docker via ssh forwarding
# Example:
# ssh -i deployer_rsa -nNT -L 2375:127.0.0.1:2375 ec2-user@18.188.106.173
# export DOCKER_HOST=tcp://localhost:2375
# docker image ls
tee /etc/docker/daemon.json << EOF
{
  "hosts": [
    "tcp://0.0.0.0:2375",
    "unix:///var/run/docker.sock"
  ]
}
EOF

service docker restart
usermod -a -G docker ec2-user

docker swarm init